name: recollect_utils
description: "All you'll ever need to create windows applications"
version: 0.0.1
homepage: https://recollect.cc
topics:
  - extensions
  - utilities
  - widgets
  - datatypes
  - functions

environment:
  sdk: ^3.10.8
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  unicode: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: RecollectPluginCApi
