name: recollect_utils
description: "All you'll ever need to create windows applications"
version: 1.2.5
publish_to: https://pub.recollect.cc
homepage: https://recollect.cc
repository: https://github.com/Seb2104/recollect_utils.git
topics:
  - extensions
  - utilities
  - widgets
  - datatypes
  - functions

environment:
  sdk: ^3.10.8
  flutter: '>=3.10.8'

dependencies:
  flutter:
    sdk: flutter
  unicode: ^1.1.9
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: RecollectUtilsPluginCApi
